qcacld-3.0: fix unused function 'dp_peer_get_ref_find_by_addr'
./drivers/net/wireless/qualcomm/qcacld-3.0/../qca-wifi-host-cmn/dp/wifi3.0/dp_main.c:10804:1: error: unused function 'dp_peer_get_ref_find_by_addr' [-Werror,-Wunused-function]

10804 | dp_peer_get_ref_find_by_addr(struct cdp_pdev *dev, uint8_t *peer_mac_addr,

      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~1

 error generated.

Reported-by: Z3phery <dz.ignacioaguilar@gmail.com>