kernel: sys: use bitwise for LINUX_VERSION_*
The compiler freaks out using a undeclared identifier so this error is thrown

../kernel/sys.c:1304:5: error: use of undeclared identifier 'LINUX_VERSION_MAJOR'
 1304 |                          LINUX_VERSION_MAJOR, LINUX_VERSION_PATCHLEVEL,
      |                          ^
../kernel/sys.c:1304:26: error: use of undeclared identifier 'LINUX_VERSION_PATCHLEVEL'
 1304 |                          LINUX_VERSION_MAJOR, LINUX_VERSION_PATCHLEVEL,
      |                                               ^
../kernel/sys.c:1305:5: error: use of undeclared identifier 'LINUX_VERSION_SUBLEVEL'
 1305 |                          LINUX_VERSION_SUBLEVEL);
      |                          ^
3 errors generated.

Use bitwise shifts to mitigate this issue

Fixes: 93f667a55a62 ("kernel/sys.c: Strip localversion from uname for GMS processes")
Signed-off-by: Josh Law <joshlaw48@gmail.com>
Tested-by: Josh Law <joshlaw48@gmail.com>