security: selinux: ksu: Define missing susfs_kernel_sid
Fixes the following compilation error:
ld.lld: error: undefined symbol: susfs_kernel_sid

Signed-off-by: odd
Signed-off-by: techyguyperplexable <objecting@objecting.org>